import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

function toCsvValue(value) {
  const str = String(value ?? "");
  if (/[",\n]/.test(str)) {
    return '"' + str.replace(/"/g, '""') + '"';
  }
  return str;
}

export function exportToCSV(rows, columns, filename) {
  const header = columns.map((c) => toCsvValue(c.label)).join(",");
  const body = rows
    .map((row) => columns.map((c) => toCsvValue(row[c.key])).join(","))
    .join("\n");
  const csv = header + "\n" + body;

  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename.endsWith(".csv") ? filename : filename + ".csv";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportToPDF({ title, subtitle, columns, rows, filename }) {
  const doc = new jsPDF();

  doc.setFontSize(18);
  doc.setTextColor(20, 20, 20);
  doc.text(title, 14, 20);

  if (subtitle) {
    doc.setFontSize(10);
    doc.setTextColor(120, 120, 120);
    doc.text(subtitle, 14, 27);
  }

  autoTable(doc, {
    startY: subtitle ? 33 : 28,
    head: [columns.map((c) => c.label)],
    body: rows.map((row) => columns.map((c) => String(row[c.key] ?? ""))),
    headStyles: { fillColor: [0, 197, 143] },
    styles: { fontSize: 9, cellPadding: 4 },
    theme: "striped",
  });

  const pageCount = doc.internal.getNumberOfPages();
  doc.setFontSize(8);
  doc.setTextColor(160, 160, 160);
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.text(
      `Generated by VORTEX - ${new Date().toLocaleDateString()} - Page ${i}/${pageCount}`,
      14,
      doc.internal.pageSize.getHeight() - 10
    );
  }

  doc.save(filename.endsWith(".pdf") ? filename : filename + ".pdf");
}

export function exportTextPDF({ title, paragraphs, filename }) {
  const doc = new jsPDF();
  const marginX = 14;
  const pageWidth = doc.internal.pageSize.getWidth();
  const maxWidth = pageWidth - marginX * 2;

  doc.setFontSize(20);
  doc.setTextColor(0, 197, 143);
  doc.text(title, marginX, 22);

  doc.setDrawColor(0, 197, 143);
  doc.line(marginX, 27, pageWidth - marginX, 27);

  let y = 40;
  doc.setFontSize(11);
  doc.setTextColor(30, 30, 30);
  paragraphs.forEach((p) => {
    const lines = doc.splitTextToSize(p, maxWidth);
    doc.text(lines, marginX, y);
    y += lines.length * 6 + 8;
  });

  doc.setFontSize(8);
  doc.setTextColor(160, 160, 160);
  doc.text(`Generated by VORTEX - ${new Date().toLocaleDateString()}`, marginX, doc.internal.pageSize.getHeight() - 10);

  doc.save(filename.endsWith(".pdf") ? filename : filename + ".pdf");
}
